<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Zyw5Lqn6KaB6Ze7');
$cfg_Cs[2]=array(1,1,1,'SFRNTA==');
$cfg_Cs[3]=array(1,1,1,'RElWJkNTUw==');
$cfg_Cs[4]=array(1,1,1,'SmF2YXNjcmlwdC9BamF4');
$cfg_Cs[5]=array(1,1,1,'RHJlYW13ZWF2ZXI=');
$cfg_Cs[6]=array(0,2,1,'56uZ6ZW/5Zu+6ZuG');
$cfg_Cs[7]=array(0,3,1,'6L2v5Lu25LiL6L29');
$cfg_Cs[8]=array(0,6,1,'5oi/5Lqn5bGV6KeI');
$cfg_Cs[15]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[12]=array(1,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[13]=array(1,1,1,'IOaIkeS7rOeahOS8mOWKvyAJ');
$cfg_Cs[14]=array(1,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[16]=array(0,1,1,'5pyN5Yqh6aG555uu');
?>