<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(17,1,1,'5Zyw5Lqn6KaB6Ze7');
$cfg_Cs[6]=array(0,2,1,'56uZ6ZW/5Zu+6ZuG');
$cfg_Cs[7]=array(0,3,1,'6L2v5Lu25LiL6L29');
$cfg_Cs[8]=array(0,1,1,'RW5saXNo');
$cfg_Cs[15]=array(17,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[16]=array(17,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[17]=array(0,1,1,'5Lit5paH');
$cfg_Cs[18]=array(17,6,1,'5oi/5bGL5bGV56S6');
$cfg_Cs[19]=array(8,1,1,'c2VydmljZXM=');
$cfg_Cs[20]=array(8,6,1,'cG9ydGZvbGlvcw==');
$cfg_Cs[21]=array(8,1,1,'TmV3cw==');
$cfg_Cs[22]=array(8,1,1,'Q29udGFjdCBVcw==');
?>