<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",45,199);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",256,271);
$z[2]=Array("title","",287,301);
$z[3]=Array("pubdate","",364,410);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",466,484);
$z[5]=Array("brand","",541,555);
$z[6]=Array("click","",606,620);
$z[7]=Array("description","",706,726);

?>