<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",45,199);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",249,264);
$z[2]=Array("title","",280,294);
$z[3]=Array("pubdate","",386,432);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",481,499);
$z[5]=Array("brand","",548,562);
$z[6]=Array("click","",609,623);
$z[7]=Array("description","",734,754);

?>