<?php
$z[0]=Array("field","",240,259);
$z[0][4]['name']="title";
$z[1]=Array("global","",260,286);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",438,460);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",500,551);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",756,788);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",846,878);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",925,960);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",1101,1133);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("channel","\r\n<A class=green \r\nhref=\"[field:typeurl/]\">[field:typename/]</A>\r\n",1340,1540);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[9]=Array("field","",1585,1604);
$z[9][4]['name']="title";
$z[10]=Array("field","",1711,1763);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("field","",1861,1879);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",2672,2697);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",2703,2729);
$z[13][4]['get']="next";
$z[14]=Array("include","",2820,2857);
$z[14][4]['filename']="footer.htm";

?>