<DIV class=grid><STRONG><A title=[field:title/] 
href="[field:arcurl/]" 
target=_blank>[field:title/]</A></STRONG> 
<DIV class=imgholder><A title=[field:title/] 
href="[field:arcurl/]" target=_blank><IMG 
src="[field:litpic/]"></A></DIV>
<P><A title=[field:title/] href="[field:arcurl/]" 
target=_blank>[field:info/]..</A></P>
<DIV class=meta><SPAN>[field:typelink/]</SPAN><A title=[field:title/] 
href="[field:arcurl/]" 
target=_blank><B></B></A></DIV></DIV>