<?php
$z[0]=Array("title","",33,47);
$z[1]=Array("arcurl","",56,71);
$z[2]=Array("title","",89,103);
$z[3]=Array("title","",149,163);
$z[4]=Array("arcurl","",172,187);
$z[5]=Array("litpic","",215,230);
$z[6]=Array("title","",256,270);
$z[7]=Array("arcurl","",277,292);
$z[8]=Array("info","",310,323);
$z[9]=Array("typelink","",357,374);
$z[10]=Array("title","",390,404);
$z[11]=Array("arcurl","",413,428);

?>