<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",57,211);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",297,312);
$z[2]=Array("title","",328,342);
$z[3]=Array("pubdate","",409,455);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",519,537);
$z[5]=Array("trueprice","",602,620);
$z[6]=Array("brand","",681,695);
$z[7]=Array("click","",750,764);
$z[8]=Array("description","",872,892);

?>