<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",45,199);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",226,241);
$z[2]=Array("title","",257,271);
$z[3]=Array("pubdate","",336,382);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",417,435);
$z[5]=Array("brand","",470,484);
$z[6]=Array("click","",517,531);
$z[7]=Array("description","",605,625);

?>