<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",45,199);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",269,284);
$z[2]=Array("title","",300,314);
$z[3]=Array("pubdate","",377,423);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",479,497);
$z[5]=Array("brand","",554,568);
$z[6]=Array("click","",619,633);
$z[7]=Array("description","",719,739);

?>