<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",22,176);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",203,218);
$z[2]=Array("title","",234,248);
$z[3]=Array("pubdate","",310,356);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",388,406);
$z[5]=Array("brand","",438,452);
$z[6]=Array("click","",484,498);
$z[7]=Array("description","",569,589);

?>