<?php
$z[0]=Array("global","",168,200);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",394,426);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",626,658);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("type","[field:typelink/]",713,763);
$z[3][4]['typeid']="17";
$z[4]=Array("type","[field:typelink/]",802,851);
$z[4][4]['typeid']="8";
$z[5]=Array("global","",972,1004);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1130,1155);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channel","\r\n  <LI class=menu201><A title=[field:typename/] href=\"[field:typeurl/]\">[field:typename/]</A> \r\n  </LI>\r\n",1182,1430);
$z[7][4]['typeid']="8";
$z[7][4]['row']="10";
$z[7][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>