<?php
$z[0]=Array("global","",157,182);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",248,273);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",335,360);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",393,419);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",547,574);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",647,674);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",677,703);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",862,889);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",901,933);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",980,1006);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1061,1098);
$z[10][4]['name']="contentTopBanner1";
$z[11]=Array("myad","",1133,1170);
$z[11][4]['name']="contentTopBanner2";
$z[12]=Array("global","",1473,1498);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1538,1781);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",1873,1898);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2706,2836);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>