<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",45,199);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",284,299);
$z[2]=Array("title","",315,329);
$z[3]=Array("pubdate","",392,438);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",494,512);
$z[5]=Array("brand","",569,583);
$z[6]=Array("click","",634,648);
$z[7]=Array("description","",734,754);

?>