<?php
$z[0]=Array("global","",106,133);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",135,161);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("myad","",236,265);
$z[2][4]['name']="topbanner";
$z[3]=Array("global","",372,400);
$z[3][4]['name']="cfg_memberurl";
$z[4]=Array("global","",459,484);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",549,575);
$z[5][4]['name']="cfg_dataurl";
$z[6]=Array("global","",647,673);
$z[6][4]['name']="cfg_dataurl";
$z[7]=Array("global","",888,913);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>",943,1131);
$z[8][4]['type']="top";
$z[8][4]['currentstyle']="<li class='thisclass'><a href='~typelink~'>~typename~</a> </li>";
$z[9]=Array("field","",1272,1299);
$z[9][4]['name']="phpurl";
$z[10]=Array("tag","<li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2005,2120);
$z[10][4]['row']="8";
$z[10][4]['getall']="1";
$z[10][4]['sort']="month";

?>