<?php
$z[0]=Array("global","",187,219);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",413,445);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",669,701);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("type","[field:typelink/]",754,804);
$z[3][4]['typeid']="17";
$z[4]=Array("type","[field:typelink/]",843,892);
$z[4][4]['typeid']="8";
$z[5]=Array("global","",1043,1075);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1216,1241);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channel","\r\n  <LI class=menu201><A title=[field:typename/] href=\"[field:typeurl/]\">[field:typename/]</A> \r\n  </LI>\r\n",1276,1525);
$z[7][4]['typeid']="17";
$z[7][4]['row']="10";
$z[7][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>