<?php
$z[0]=Array("global","",187,219);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",413,445);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",669,701);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",862,894);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1035,1060);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n  <LI class=menu201><A title=[field:typename/] href=\"[field:typeurl/]\">[field:typename/]</A> \r\n  </LI>\r\n",1095,1343);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>