<?php
$z[0]=Array("field","",240,259);
$z[0][4]['name']="title";
$z[1]=Array("global","",260,286);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",438,467);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",507,565);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",770,802);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",858,890);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",937,972);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",1111,1143);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("channel","\r\n<A class=green \r\nhref=\"[field:typeurl/]\">[field:typename/]</A>\r\n",1350,1550);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[9]=Array("list","\r\n  <LI><A title=[field:title/] \r\n  href=\"[field:arcurl/]\"><SPAN \r\n  class=title>[field:title/]</SPAN><SPAN class=rq>日期：20[field:pubdate function=\"GetDateMK(@me)\"/]</SPAN><SPAN \r\n  class=xwnr>[field:description/]...</SPAN></A></LI>\r\n",1613,1889);
$z[9][4]['pagesize']="12";
$z[10]=Array("pagelist","",1937,2015);
$z[10][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",2089,2126);
$z[11][4]['filename']="footer.htm";

?>