<?php
$z[0]=Array("field","",240,259);
$z[0][4]['name']="title";
$z[1]=Array("global","",260,286);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",438,460);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",500,551);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",756,788);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",844,876);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",923,958);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",1097,1129);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("channel","\r\n<A class=green \r\nhref=\"[field:typeurl/]\">[field:typename/]</A>\r\n",1339,1539);
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[9]=Array("field","",1570,1591);
$z[9][4]['name']="content";
$z[10]=Array("include","",1674,1711);
$z[10][4]['filename']="footer.htm";

?>